[package]
name = "executor"
version = "0.1.0"
edition = "2024"

[dependencies]
executor-macros = { path = "../executor-macros", optional = true }

[features]
default = ["std"]
std = ["executor-macros"]